#MODULES
import random
from lists import * #words and common, from another file

#THE CLASS STRUCTURE(S)

#TODO: Potentially master username/password and inherit username into class password
class superLogin():
    def __init__(self):
        self._username = ""
        self._password = ""

    #getters
    def getUsername(self):
        return self._username
    
    def getPassword(self):
        #this is where RSA decryption would go
        temp = ''
        temp = self._password 
        return temp 
    
    #setters
    def setUsername(self, username):
        self._username = username

    def setPassword(self, password):
        self._password = password

    #polymorphism custom print function
    def __str__(self):
        outputstring = ""
        outputstring += str(self._username) + " " + str(self._password)
        return outputstring
    
class Password(superLogin):

    def __init__(self):
        superLogin.__init__(self)  
        
        self._service = ""         #service that the password is being stored for
        
        self._password = str(self.generatePassword()) 
        #self.validatePassword() #FIXME:infinite loop
        
        #autogenerated strength/time to crack (in years)
        self._strength = self.timeTaken()

    def generatePassword(self):
        
        #local variables
        generated = ['']*3

        password = ''

        #generate three word password and add on num/ special characters inbetween
    
        #generate words
        for i in range(len(generated)):
            generated[i] = (words[random.randint(0,len(words)-1)]).capitalize()
        
        #add them to password
        for i in range(len(generated)):
            password += generated[i]
        
            for x in range(random.randint(0,3)):
                password += chr(random.randint(48,57))

        #makes sure password is greater than 12 characters
        if len(password) < 12:
            for x in range(12-len(password)):
                password += chr(random.randint(48,57))

        #TODO: make sure it isnt too long
                
        #this is where RSA encryption would go probably
            
        return password

    def validatePassword(self):
        password = self._password
        
        valid = False
    
        while not valid:
            # Checks if password generated matches any common passwords or if it's empty, or if its too long and hard to memorise                                                       
            if any(substring in password.lower() for substring  in common) or password =="" or len(password)>20:
                # and regenerates it if it does
                self._password = self.generatePassword()
                print("testloop")
            else:
                valid = True
        


    def timeTaken(self):
        password = self._password
        length = len(password)
        ways = (26*2 + 21)  ** length
        seconds = ways / 1000000000     # assuming a password cracker can attempt 1bn passwords per second
        days = seconds / 86400          # 86400 seconds in a day
        years = days / 365              # 365 days in a year, not including leap days

        timeToCrack = round(years,2)

        return timeToCrack
        
    #GETTER METHODS

    def getService(self):
        return self._service
    
    def getStrength(self):
        return self._strength

    #SETTER METHODS
    
    def setService(self, service):
        self._service = service

    def setTimeTaken(self, timeTaken):
        self._timeTaken = timeTaken
    
    #CUSTOM PRINT FUNCTION POLYMORPHISM
    def __str__(self):
        outputstring = ""
        outputstring += str(self._username) + " " + str(self._service) + " " + str(self._password) + " " + str(self._strength)
        return outputstring

#FILE HANDLING
def readLoginCSV(file):
    users = []
    with open(file) as readfile:    #prepares to read data from text file 
        line = readfile.readline().rstrip('\n')

        while line: #repeats for every line
            items = line.split(",")

            user= superLogin()
            
            username= str(items[0])
            password = str(items[1])

            user.setUsername(username)
            user.setPassword(password)

            users.append(user)
            line = readfile.readline().rstrip('\n')   

    return users  

def readPasswordsCSV(file, masterusername): #master username is the current user that is active
    details = []
    with open(file) as readfile:    #prepares to read data from text file 
        line = readfile.readline().rstrip('\n')

        while line: #repeats for every line
            items = line.split(",") #splits items up
            
            #get username
            username= str(items[0])

            #see if password belongs to the user logged in (masterusername)
            if username == masterusername:
                
                #read in rest to array of objects
                password = str(items[1])
                service = str(items[2])
                strength = float(items[3])
                
                #create instance of object
                detail= Password()

                #use setter methods
                detail.setUsername(username)
                detail.setPassword(password)
                detail.setService(service)
                detail.setTimeTaken(strength)

                #add object to array
                details.append(detail)
            
            #next line
            line = readfile.readline().rstrip('\n')   

    #TODO: what happens if user cannot be found??? we must have validation beforehand to check that the user is present in the file, but this will happen when validating the login 
    return details  

#ALGORITHMS
def sortArrayObjects(list):
    value = 0
    index = 0
    for i in range(1,len(list)):
        value = list[i]   #double check oop sorting
        index = i
        while index > 0 and value.getService() < list[index-1].getService():
            list[index]=list[index-1]  
            index = index-1
        list[index] = value

    return list

def validateLogin(inputUser,inputPass,users):   #TODO:change to binary search
    valid = False
    for i in range(len(users)): 
        if users[i].getUsername() == inputUser and users[i].getPassword() == inputPass: #compare current username and password
            valid = True

    return valid


#NEW PASSWORD THINGS
def addPasswordArray(masterusername,service,details,file):
    detail= Password()

    #use setter methods
    detail.setUsername(masterusername)
    detail.setService(service)
    #password and time taken will auto generate

    #add object to array
    details.append(detail)
    details = sortArrayObjects(details) #sort password details into ascending password order, do this every time a new password is added
    writePassword(file,details)

    return details

def writePassword(file,details):    #FIXME: resets for new users
    DataFile = open(file, 'w')
    for i in range(len(details)):
        DataFile.write(details[i].getUsername() + "," + details[i].getPassword() + "," + details[i].getService() + "," + str(details[i].getStrength())+"\n")  
    DataFile.close() 

#FIND PASSWORD
def findPassword(goal,details):
    found = False
    startpos = 0
    endpos = len(details)-1

    while (startpos <= endpos) and found == False:
        
        middle = (startpos+endpos)//2 #// is integer div
        
        if details[middle].getService() == goal:
            found = True
            print(details[middle].getPassword())
            return middle
            
        elif details[middle].getService() <goal:
            startpos = middle + 1
        else:
            endpos = middle - 1

    if found == False:
        print("not found")
        return -1

#MAIN

#read in data to array for login
file = "login.csv"
users = readLoginCSV(file)

#recieve inputs
inputUser = str(input("input username: "))
inputPass = str(input("input password: "))

#set masterusername after login validation

while validateLogin(inputUser,inputPass,users) != True:
    print("invalid")
    inputUser = str(input("input username: "))
    inputPass = str(input("input password: "))

if validateLogin(inputUser,inputPass,users) == True:    
    print("valid")
    masterusername = inputUser

file = "passwords.csv"
details = readPasswordsCSV(file,masterusername)
for i in range(len(details)):
    print(details[i])


#loop to simulate the program, able to keep repeating actions, add password or find password
choice = ""
while True:
    choice = str(input("---------------------\nn for new password \nf to display password\nr to reggenerate\nexit to quit\n"))
    if choice == "exit":
        break
    elif choice == 'n':
        service = str(input("service to add a password to: "))
        details = addPasswordArray(masterusername,service,details,file)

        #print out array
        for i in range(len(details)):
            print(details[i].getService())
            
    elif choice =='f':
        goal = str(input("What is the service of the password you are searching for?: "))
        index = findPassword(goal,details)
        print(index)
    elif choice == 'r':
        goal = str(input("What is the service of the password you are wanting to regenerate?: "))
        index = findPassword(goal,details)
        print(details[index].generatePassword())
        #TODO: doesn't work
    else:
        print("invalid choice")
        


"""TODO:

- password validation with common passwords
- fix file issue
- RSA
- log out
- integration with WEB not calculus you fool

okay so the array is going to be filled on user log in, so that it only stores the details for the current active user
will check the first element read in from file and see if it matches the master username

username is master username in all cases


username    password    service     strength



"""
